apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: dev-rhombus
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
  MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
